inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - docs/**/*
    - vendor/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false
